name: Update Browserslist DB

on:
  workflow_dispatch: {}   # run it manually from the Actions tab

permissions:
  contents: write

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (clean)
        run: npm ci

      - name: Update Browserslist DB (caniuse-lite)
        run: npx browserslist@latest --update-db

      - name: Commit changes (if any)
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json package.json || true
            git commit -m "chore: update Browserslist DB (caniuse-lite)"
            git push
          else
            echo "No changes to commit."
          fi
