name: Update package-lock after pkg.json edits

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Regenerate package-lock.json (no install)
        run: |
          npm config set fund false
          npm config set audit false
          npm install --package-lock-only --legacy-peer-deps

      - name: Commit lockfile changes
        run: |
          if [[ -n "$(git status --porcelain package-lock.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore: update package-lock after esbuild overrides"
            git push
          else
            echo "No lockfile changes."
          fi

